In [229]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [230]:
data =pd.read_csv("/Users/steafen/Desktop/data2.csv")
data

,SiO2,Na2O,K2O,CaO,MgO,Al2O3,Fe2O3,CuO,PbO,BaO,P2O5,SrO,SnO2,SO2,Wenshi,Type,color,Fenghua
0,69.33,0.00,9.99,6.32,0.87,3.93,1.74,3.87,0.00,0.00,1.17,0.00,0.0,0.39,3,0,1,0
1,36.28,0.00,1.05,2.34,1.18,5.73,1.86,0.26,47.43,0.00,3.57,0.19,0.0,0.00,1,1,2,1
2,87.05,0.00,5.19,2.01,0.00,4.06,0.00,0.78,0.25,0.00,0.66,0.00,0.0,0.00,1,0,1,0
3,61.71,0.00,12.37,5.87,1.11,5.50,2.16,5.09,1.41,2.86,0.70,0.10,0.0,0.00,1,0,1,0
4,65.88,0.00,9.67,7.12,1.56,6.44,2.06,2.18,0.00,0.00,0.79,0.00,0.0,0.36,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,17.11,0.00,0.00,0.00,1.11,3.65,0.00,1.34,58.46,0.00,14.13,1.12,0.0,0.00,3,1,2,1
63,49.01,2.71,0.00,1.13,0.00,1.45,0.00,0.86,32.92,7.95,0.35,0.00,0.0,0.00,3,1,8,0
64,29.15,0.00,0.00,1.21,0.00,1.85,0.00,0.79,41.25,15.45,2.54,0.00,0.0,0.00,3,1,1,1
65,25.42,0.00,0.00,1.31,0.00,2.18,0.00,1.16,45.10,17.30,0.00,0.00,0.0,0.00,3,1,1,1
66,30.39,0.00,0.34,3.49,0.79,3.52,0.86,3.13,39.35,7.66,8.99,0.24,0.0,0.00,3,1,0,1

In [231]:
x_data=data.drop(["Type","color","Wenshi"],axis=1)
x_data

,SiO2,Na2O,K2O,CaO,MgO,Al2O3,Fe2O3,CuO,PbO,BaO,P2O5,SrO,SnO2,SO2,Fenghua
0,69.33,0.00,9.99,6.32,0.87,3.93,1.74,3.87,0.00,0.00,1.17,0.00,0.0,0.39,0
1,36.28,0.00,1.05,2.34,1.18,5.73,1.86,0.26,47.43,0.00,3.57,0.19,0.0,0.00,1
2,87.05,0.00,5.19,2.01,0.00,4.06,0.00,0.78,0.25,0.00,0.66,0.00,0.0,0.00,0
3,61.71,0.00,12.37,5.87,1.11,5.50,2.16,5.09,1.41,2.86,0.70,0.10,0.0,0.00,0
4,65.88,0.00,9.67,7.12,1.56,6.44,2.06,2.18,0.00,0.00,0.79,0.00,0.0,0.36,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,17.11,0.00,0.00,0.00,1.11,3.65,0.00,1.34,58.46,0.00,14.13,1.12,0.0,0.00,1
63,49.01,2.71,0.00,1.13,0.00,1.45,0.00,0.86,32.92,7.95,0.35,0.00,0.0,0.00,0
64,29.15,0.00,0.00,1.21,0.00,1.85,0.00,0.79,41.25,15.45,2.54,0.00,0.0,0.00,1
65,25.42,0.00,0.00,1.31,0.00,2.18,0.00,1.16,45.10,17.30,0.00,0.00,0.0,0.00,1
66,30.39,0.00,0.34,3.49,0.79,3.52,0.86,3.13,39.35,7.66,8.99,0.24,0.0,0.00,1

In [232]:
y_data=data.iloc[:,-3]
y_data

0     0
1     1
2     0
3     0
4     0
     ..
62    1
63    1
64    1
65    1
66    1
Name: Type, Length: 67, dtype: int64

In [233]:
model=LogisticRegression()
model.fit(x_data,y_data)
print(model.intercept_)
print(model.coef_)

[5.76807543]
[[-1.36986381e-01  2.11805602e-02 -2.50582873e-01 -1.09124487e-01
  -5.86812672e-03  4.36940482e-02 -6.52444686e-02 -7.71903247e-02
   5.44901172e-01  1.17595125e-01 -5.50004134e-02  5.22707159e-03
  -4.87920301e-04 -1.10263800e-04  2.03730820e-02]]

In [234]:
x_data.iloc[10].values

test=x_data.iloc[10].values.reshape(1,-1)
test

array([[ 4.61,  0.  ,  0.  ,  3.19,  0.  ,  1.11,  0.  ,  3.14, 32.45,
        30.62,  7.56,  0.53,  0.  , 15.03,  1.  ]])

In [235]:
print(model.predict(test)[0])

1

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

è¿›è¡Œé¢„æµ‹

In [257]:
data_test =pd.read_csv("/Users/steafen/Desktop/data3.csv",header=None)
data_test

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0,78.45,0.0,0.00,6.08,1.86,7.23,2.15,2.11,0.00,0.00,1.06,0.03,0.00,0.51
1,1,37.75,0.0,0.00,7.63,0.00,2.33,0.00,0.00,34.30,0.00,14.27,0.00,0.00,0.00
2,0,31.95,0.0,1.36,7.19,0.81,2.93,7.06,0.21,39.58,4.69,2.68,0.52,0.00,0.00
3,0,35.47,0.0,0.79,2.89,1.05,7.07,6.45,0.96,24.28,8.31,8.45,0.28,0.00,0.00
4,1,64.29,1.2,0.37,1.64,2.34,12.75,0.81,0.94,12.23,2.16,0.19,0.21,0.49,0.00
5,1,93.17,0.0,1.35,0.64,0.21,1.52,0.27,1.73,0.00,0.00,0.21,0.00,0.00,0.00
6,1,90.83,0.0,0.98,1.12,0.00,5.06,0.24,1.17,0.00,0.00,0.13,0.00,0.00,0.11
7,0,51.12,0.0,0.23,0.89,0.00,2.12,0.00,9.01,21.24,11.34,1.46,0.31,0.00,2.26

In [275]:
fenghua=data_test.loc[:,0]
print(fenghua)
#pd.concat(['data_test','fenghua'],axis=1)
data_test.drop(0,axis=1,inplace=True)
data_test=pd.concat([data_test,fenghua],axis=1)
test_x=data_test.loc[7].values.reshape(1,-1)
test_x

0    0
1    1
2    0
3    0
4    1
5    1
6    1
7    0
Name: 0, dtype: int64

array([[51.12,  0.  ,  0.23,  0.89,  0.  ,  2.12,  0.  ,  9.01, 21.24,
        11.34,  1.46,  0.31,  0.  ,  2.26,  0.  ]])

In [276]:
print(model.predict(test_x)[0])

1

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [239]:
accuracy_score(model.predict(x_data),y_data) # è®¡ç®—åœ¨è®­ç»ƒé›†ä¸Šçš„å‡†ç¡®åº¦

1.0

In [240]:
mse = np.mean((model.predict(x_data) - y_data) ** 2)

In [241]:
mse

0.0

In [242]:
coef=model.coef_
coef

array([[-1.36986381e-01,  2.11805602e-02, -2.50582873e-01,
        -1.09124487e-01, -5.86812672e-03,  4.36940482e-02,
        -6.52444686e-02, -7.71903247e-02,  5.44901172e-01,
         1.17595125e-01, -5.50004134e-02,  5.22707159e-03,
        -4.87920301e-04, -1.10263800e-04,  2.03730820e-02]])

In [243]:
coef[0][0]

-0.1369863807051511